[theme]
primaryColor = "#059669"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f7fb"
textColor = "#1e293b"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
